version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    # network_mode: service:db
    volumes:
      - ../..:/workspaces:cached

    command: sleep infinity

  # db:
  #   image: postgres:latest
  #   restart: unless-stopped
  #   # network_mode: service:app
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_USER: postgres
  #     POSTGRES_DB: postgres

  # pgadmin:
  #   image: dpage/pgadmin4
  #   restart: unless-stopped
  #   network_mode: service:app
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   volumes:
  #     - pgadmin-data:/var/lib/pgadmin
# volumes:
# postgres-data:
# pgadmin-data:
